name: GRASS_8_0_preview

on:
  - push
  - pull_request

jobs:
  build:
    name: ${{ matrix.os }} build and tests

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:
          - windows-2019
      fail-fast: false

    steps:
      - name: Set git to use LF
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf
      - uses: actions/checkout@v2
      - name: Install OSGeo4W
        run: |
          $exe = 'osgeo4w-setup.exe'
          $url = 'http://download.osgeo.org/osgeo4w/v2/' + $exe
          (New-Object System.Net.WebClient).DownloadFile($url, $exe)
          Start-Process ('.\'+$exe) -ArgumentList '-A -g -k -q -s http://download.osgeo.org/x86_64 -P proj-devel,gdal-devel,geos-devel,libtiff-devel,libpng-devel,pdal-devel,pdal,pdal-libs,netcdf-devel,cairo-devel,fftw,freetype-devel,gdal-ecw,gdal-mrsid,liblas-devel,libxdr,libpq-devel,pdcurses,python3-matplotlib,python3-numpy,python3-ply,python3-pywin32,python3-six,python3-wxpython,regex-devel,wxwidgets-devel,zstd-devel' -Wait
      - name: Build GRASS GIS
        working-directory: ./src/grass-dev/osgeo4w/
        run: C:\msys64\usr\bin\bash.exe -l (''+(Get-Location)+'\src\grass-dev\osgeo4w\package.sh') (Get-Location)
      - name: Test executing of the grass command
        run: .github/workflows/test_simple.bat 'C:\OSGeo4W\opt\grass\grass80.bat'
      - name: Test executing of the grass command in bash
        run: C:\msys64\usr\bin\bash.exe .github/workflows/test_simple.sh
